
package shiftssclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShiftService", targetNamespace = "http://service.legacy.apsh.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShiftService {


    /**
     * 
     * @return
     *     returns java.util.List<shiftssclient.Shift>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShiftService", targetNamespace = "http://service.legacy.apsh.com/", className = "shiftssclient.GetShiftService")
    @ResponseWrapper(localName = "getShiftServiceResponse", targetNamespace = "http://service.legacy.apsh.com/", className = "shiftssclient.GetShiftServiceResponse")
    @Action(input = "http://service.legacy.apsh.com/ShiftService/getShiftServiceRequest", output = "http://service.legacy.apsh.com/ShiftService/getShiftServiceResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.legacy.apsh.com/ShiftService/getShiftService/Fault/Exception")
    })
    public List<Shift> getShiftService()
        throws Exception_Exception
    ;

}
