
package shiftssclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShiftServiceService", targetNamespace = "http://service.legacy.apsh.com/", wsdlLocation = "http://localhost:8085/Shift?wsdl")
public class ShiftServiceService
    extends Service
{

    private final static URL SHIFTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SHIFTSERVICESERVICE_EXCEPTION;
    private final static QName SHIFTSERVICESERVICE_QNAME = new QName("http://service.legacy.apsh.com/", "ShiftServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/Shift?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHIFTSERVICESERVICE_WSDL_LOCATION = url;
        SHIFTSERVICESERVICE_EXCEPTION = e;
    }

    public ShiftServiceService() {
        super(__getWsdlLocation(), SHIFTSERVICESERVICE_QNAME);
    }

    public ShiftServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHIFTSERVICESERVICE_QNAME, features);
    }

    public ShiftServiceService(URL wsdlLocation) {
        super(wsdlLocation, SHIFTSERVICESERVICE_QNAME);
    }

    public ShiftServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHIFTSERVICESERVICE_QNAME, features);
    }

    public ShiftServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShiftServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShiftService
     */
    @WebEndpoint(name = "ShiftServicePort")
    public ShiftService getShiftServicePort() {
        return super.getPort(new QName("http://service.legacy.apsh.com/", "ShiftServicePort"), ShiftService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShiftService
     */
    @WebEndpoint(name = "ShiftServicePort")
    public ShiftService getShiftServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.legacy.apsh.com/", "ShiftServicePort"), ShiftService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHIFTSERVICESERVICE_EXCEPTION!= null) {
            throw SHIFTSERVICESERVICE_EXCEPTION;
        }
        return SHIFTSERVICESERVICE_WSDL_LOCATION;
    }

}
