language: java
jdk:
- openjdk8
services:
- docker
addons:
  ssh_known_hosts: 123.57.73.97
cache:
  directories:
  - "$HOME/.m2/repository"
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install: 
before_script: 
script:
- mvn -DskipTests clean install package
- docker build -t chph/$APSH_LEGACY_SYSTEM .
- echo -n 'Q2hwaDExNDk3NTQ4Mjk=' | base64 --decode | docker login --username=chph
  --password-stdin
- docker push chph/$APSH_LEGACY_SYSTEM
after_success: 
after_failure: 
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: scp ./kubernetes/*.yaml root@123.57.73.97:~/apsh/legacy-system/ && ssh root@123.57.73.97
    "kubectl apply -f ~/apsh/legacy-system"
  on:
    all_branches: true
after_deploy: 
after_script: 
branches:
  only:
  - dev
  - master
notifications:
  email:
    recipients:
    - 876684433@qq.com
    - chph13420146901@gmail.com
    on_success: always
    on_failure: always
env:
  global:
  - GH_REF=https://github.com/APS-H/LegacySystem.git
  - APSH_LEGACY_SYSTEM=apsh-legacy-system:v1
