legacy-system:
  employer:
    port: 9000
    context: employer
  order:
    port: 9001
    context: order
  shift:
    port: 9002
    context: shift
  erp:
    port: 9003
    context: erp
schema:
  path: /run/schemas
